# Generated by Django 5.2.7 on 2025-10-14 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categroy',
            new_name='category',
        ),
    ]
